### ISSUE TITLE
Support collecting power utilization of identified devices

### ISSUE THREAD

**Issue by davidwilemski** [ejsuncy/sense_energy_prometheus_exporter#3]
I was experimenting with this collector this evening. Very cool project!

I was a little surprised that the collector only exports the `sense_energy_power_watts` metric for the `main` and `solar` devices (total current energy usage measured on the account and the current solar production). The CSV export funtionality of the Sense web app (and it turns out the API as well) supports exporting data on a per-device level (including the "always on" and "other" buckets for unidentified devices). I was wondering whether you'd want to support exporting power usage on a device level as well as a whole house/account level? It's something I've found useful and have been using CSV exports to get hourly kwh data for but supporting ingesting realtime data with Prometheus would be super cool!

Poking around with the code you'd already written to wrap the sense client, it turned out I was able to get what I wanted by using the `get_realtime()` method on the sensable client. This method returns a dictionary with a large amount of data on various keys, one of those being `devices`:

```
>>> sense_client.accounts[0].senseable.get_realtime()['devices']
[{'id': 'always_on', 'name': 'Always On', 'icon': 'alwayson', 'tags': {'DefaultUserDeviceType': 'AlwaysOn', 'DeviceListAllowed': 'true', 'TimelineAllowed': 'false', 'UserDeleted': 'false', 'UserDeviceType': 'AlwaysOn', 'UserDeviceTypeDisp
layString': 'AlwaysOn', 'UserEditable': 'false', 'UserMergeable': 'false'}, 'attrs': [], 'w': 170.0}, {'id': 'unknown', 'name': 'Other', 'icon': 'home', 'tags': {'DefaultUserDeviceType': 'Unknown', 'DeviceListAllowed': 'true', 'TimelineAl
lowed': 'false', 'UserDeleted': 'false', 'UserDeviceType': 'Unknown', 'UserDeviceTypeDisplayString': 'Unknown', 'UserEditable': 'false', 'UserMergeable': 'false'}, 'attrs': [], 'w': 4.364805}]
```

This ends up looking to be the current utilization of the various identified devices on the account. In the example above I just see Always On and Other device usage but I expect other Sense-identified devices appear here when they are in use as well.

It ends up being a ~3 line code change to support exporting these other devices to the `sense_energy_power_watts` metric in addition to the `main` and `solar` aggregate "device names". I'm happy to submit a PR or for you to use/modify my code if this is something you wanted to support.

**Comment by ejsuncy** [comment]
Hi @davidwilemski, thanks so much for contributions! I wrote this exporter before I had any devices identified by Sense, and also I don't have any solar, so I rely on community members to help out with data. I really appreciate you looking in to this--I'll take a look at your PR and take action 👍
